export const CLIMB_BOOSTS = [
  "POV: you said \"last try\" 7 tries ago. Keep cooking.",
  "Touch grass? No. Touch crimps. Respectfully.",
  "Your beta is loading... please wait... still better than campus board chaos.",
  "If your feet cut, act like it was dynamic style points.",
  "Grip strength is temporary, good vibes are forever.",
  "Climb like your crush is definitely watching.",
  "Rest timer says 3 minutes. Ego says go now. Ignore ego.",
  "Your forearms are spicy. Breathe and continue the mission.",
  "Quiet feet arc unlocked: ninja mode activated.",
  "One clean attempt > five rage attempts. Choose peace.",
  "You are one heel hook away from a character development arc.",
  "Beta breakdance is allowed if it gets you to the chains.",
  "This route was built to be solved. So are you.",
  "Core on. Hips in. Panic off.",
  "Tiny hold, giant confidence. Full send.",
  "If the move feels illegal, it is probably the right beta.",
  "No chalk? No fear. Okay maybe a little fear.",
  "Your pump is temporary. The send screenshot is forever.",
  "Pretend the wall owes you money.",
  "Try hard face on. Doubts off.",
  "Plot twist: slow and controlled is actually stronger.",
  "Stop speedrunning the crux. Read, breathe, execute.",
  "Today is a footwork patch update. Version 2.0.",
  "You are not stuck, you are beta gathering.",
  "Even legends take hangs between attempts.",
  "If it feels awkward, congrats, you are learning.",
  "That move is not cursed, it just wants better hips.",
  "Keep tension like your phone at 1 percent battery.",
  "Small progress is still progress. We take those.",
  "Last burn energy detected. Deploy wisely.",
  "Try one weird beta. Weird beta sometimes wins.",
  "You got this. And if not, you got snacks after.",
  "Channel your inner gecko, minus the tail.",
  "Fall seven times, brush holds eight.",
  "Chaos beta only: left foot nowhere, right hand vibes.",
  "Scream internally, climb externally.",
  "This attempt is sponsored by delusion and chalk dust.",
  "You are either sending or collecting cinematic falls.",
  "Speedrun the route reading, then immediately ignore your plan.",
  "Foot slip? That was a tactical momentum reset.",
  "Campus instinct detected. Please return to civilized climbing.",
  "Go full goblin mode, but with precise toe placements.",
  "Your sequence is cursed. Cast heel-hook and try again.",
  "We do not fear the slab. We fear looking silly on slab.",
  "If the beta makes no sense, add more hip rotation.",
  "Today is 10 percent strength, 90 percent dramatic commitment.",
  "Climb like the hold names are tax deductions.",
  "One more attempt for science. Then five more for feelings.",
  "Current objective: survive pump and look cool failing.",
  "Route setter said \"technical\". You heard \"parkour\".",
  "The wall is gaslighting you. Stay calm and lock off.",
  "If in doubt, toe hook something and ask questions later.",
  "Your forearms are now QR codes. Still send.",
  "This crux is fake news. You are real.",
] as const;

