export type ClimberType =
  | "Technician"
  | "Explorer"
  | "Strategist"
  | "Flow Climber"
  | "Motivator"
  | "Grinder"
  | "Risk-Taker"
  | "Calm Connector";

export type QuizQuestion = {
  question: string;
  a: ClimberType;
  b: ClimberType;
  aL: string;
  bL: string;
};

export const QUESTION_BANK: QuizQuestion[] = [
  { question: "You just walked into the gym. First move?", a: "Technician", b: "Explorer", aL: "Quiet warm-up laps and tidy footwork", bL: "Tour the wall and try random cool problems" },
  { question: "Your project keeps spitting you off. You...", a: "Strategist", b: "Flow Climber", aL: "Film beta, split it into chunks, make a plan", bL: "Shake out, breathe, and chase a cleaner rhythm" },
  { question: "Playlist and vibes check?", a: "Motivator", b: "Calm Connector", aL: "Hype mode. Energy up, attempts up.", bL: "Chill mode. Smooth breathing and flow." },
  { question: "Crux move above the last good hold?", a: "Risk-Taker", b: "Grinder", aL: "Full commit. If I peel, I peel.", bL: "Repeat setup until it feels automatic." },
  { question: "Best climbing day feels like...", a: "Explorer", b: "Strategist", aL: "Tried 20 weird boulders and found new styles", bL: "Hit today's target and can prove progress" },
  { question: "What do you write in notes after a send?", a: "Technician", b: "Flow Climber", aL: "Heel timing, hip angle, exact foot swap", bL: "Felt snappy, calm, and in sync today" },
  { question: "Someone is wobbling on a sketchy slab. You...", a: "Grinder", b: "Calm Connector", aL: "Suggest they dial the feet and try it again", bL: "Stay quiet and let them figure it out" },
  { question: "A hold looks greasy. Do you...", a: "Technician", b: "Risk-Taker", aL: "Brush it, chalk, and trust the process", bL: "Send anyway and hope the chalk gods smile" },
  { question: "Your buddy is stuck in a plateau. You...", a: "Motivator", b: "Explorer", aL: "Pump them up and cheer until they stick it", bL: "Suggest weird beta or a different wall" },
  { question: "Before a comp or big send, you prefer to...", a: "Strategist", b: "Risk-Taker", aL: "Run the beta in your head and stick to the plan", bL: "Warm up, breathe, and go for it" },
  { question: "Rest day and you are antsy. You...", a: "Explorer", b: "Technician", aL: "Watch comp videos and study beta", bL: "Stretch, hangboard lightly, or skip" },
  { question: "You fell at the same move five times. Next?", a: "Grinder", b: "Flow Climber", aL: "One more burn with tiny tweaks", bL: "Walk away and come back fresh" },
  { question: "A stranger asks for beta. You...", a: "Calm Connector", b: "Motivator", aL: "Give a short hint and let them try", bL: "Walk them through the whole sequence" },
  { question: "Your fingers are fried. You...", a: "Strategist", b: "Risk-Taker", aL: "Switch to easier climbs or skills work", bL: "Push one more hard attempt" },
  { question: "Someone flashes your project. You...", a: "Explorer", b: "Technician", aL: "Ask what beta they used", bL: "Nod, chalk up, and keep trying" },
  { question: "Warm-up feels off. You...", a: "Flow Climber", b: "Grinder", aL: "Take extra time and skip grades", bL: "Stick to the plan and push through" },
  { question: "You are about to try a dyno. You...", a: "Risk-Taker", b: "Strategist", aL: "Commit and go", bL: "Mark the landing hold and plan the swing" },
  { question: "Gym is packed. You...", a: "Calm Connector", b: "Motivator", aL: "Find a quieter corner or wait", bL: "Join a group and make it social" },
  { question: "You keep cutting feet. You...", a: "Technician", b: "Flow Climber", aL: "Film and check foot placement", bL: "Relax the grip and trust the core" },
  { question: "New gym opened. First visit you...", a: "Explorer", b: "Grinder", aL: "Wander every wall and sample", bL: "Find one project and dig in" },
  { question: "Your partner wants to leave early. You...", a: "Motivator", b: "Strategist", aL: "Convince them to stay one more", bL: "Plan a shorter session next time" },
  { question: "Crimpy problem vs slopey. You pick...", a: "Technician", b: "Flow Climber", aL: "Crimpy — precision feels good", bL: "Slopey — body tension is fun" },
  { question: "You are nervous before a lead. You...", a: "Calm Connector", b: "Risk-Taker", aL: "Breathe and visualize the clip", bL: "Pull on and trust the training" },
  { question: "Route feels sandbagged. You...", a: "Grinder", b: "Explorer", aL: "Keep at it until it goes", bL: "Try something else and come back" },
  { question: "Session goals: you usually...", a: "Strategist", b: "Flow Climber", aL: "Set a target (grade or send count)", bL: "Go with the flow and see what happens" },
  { question: "Someone is spraying beta. You...", a: "Calm Connector", b: "Technician", aL: "Nod and try it your way", bL: "Listen and test their idea" },
  { question: "You are close to a new grade. You...", a: "Motivator", b: "Grinder", aL: "Get pumped and go for it", bL: "Work the moves until they feel easy" },
  { question: "Best training partner is...", a: "Explorer", b: "Strategist", aL: "Someone who tries everything", bL: "Someone with a clear plan" },
  { question: "You are tired mid-session. You...", a: "Flow Climber", b: "Risk-Taker", aL: "Downshift and enjoy easy climbs", bL: "Rest, then one last hard go" },
  { question: "Crowd gathers for your project. You...", a: "Calm Connector", b: "Motivator", aL: "Ignore them and climb", bL: "Use the energy and send" },
  { question: "First attempt on a comp-style boulder. You...", a: "Explorer", b: "Strategist", aL: "Jump on and learn by feeling", bL: "Read every move before touching holds" },
  { question: "You slipped at the top. Next go you...", a: "Technician", b: "Risk-Taker", aL: "Adjust toe angle and center of mass", bL: "Hit it harder with more commitment" },
  { question: "Long queue at your project. You...", a: "Calm Connector", b: "Grinder", aL: "Rotate politely and keep chill", bL: "Stay nearby and keep taking turns" },
  { question: "A move feels impossible. You...", a: "Strategist", b: "Motivator", aL: "Break it into drills and links", bL: "Tell yourself you can stick it this go" },
  { question: "At slab, your default mindset is...", a: "Flow Climber", b: "Technician", aL: "Soft knees and smooth weight shifts", bL: "Exact feet, exact hips, no wasted motion" },
  { question: "You sent something hard. Celebration style?", a: "Motivator", b: "Calm Connector", aL: "Big grin, big high-fives", bL: "Quiet smile and fist bump" },
  { question: "A setter asks for feedback. You...", a: "Explorer", b: "Technician", aL: "Share how fun and creative it felt", bL: "Share specific move quality notes" },
  { question: "After a bad session, you...", a: "Grinder", b: "Flow Climber", aL: "Book another session soon and reset", bL: "Take a breather and return when fresh" },
  { question: "You watch someone send your project. You focus on...", a: "Strategist", b: "Risk-Taker", aL: "Sequence details and pacing", bL: "Where they committed hardest" },
  { question: "On overhangs, you rely most on...", a: "Technician", b: "Explorer", aL: "Heel-toe precision and tension", bL: "Trying different body shapes quickly" },
  { question: "You forgot chalk. You...", a: "Risk-Taker", b: "Strategist", aL: "Climb anyway and adapt", bL: "Borrow some and adjust session goals" },
  { question: "New climber asks 'what grade should I start?' You say...", a: "Calm Connector", b: "Motivator", aL: "Start easy and build confidence", bL: "Start fun and keep trying things" },
  { question: "You only have 35 minutes. You...", a: "Strategist", b: "Explorer", aL: "Run a short focused circuit", bL: "Sample a little of everything" },
  { question: "On a sketchy heel hook, you...", a: "Grinder", b: "Risk-Taker", aL: "Repeat until it feels locked", bL: "Trust it once and explode upward" },
  { question: "Your ideal beta advice is...", a: "Technician", b: "Flow Climber", aL: "Specific and technical", bL: "Simple cue: relax and move" },
  { question: "You keep dabbling many climbs. Friend says focus. You...", a: "Explorer", b: "Grinder", aL: "Keep roaming, variety teaches me", bL: "Pick one and finish it" },
  { question: "Your forearms start pumping. You...", a: "Flow Climber", b: "Strategist", aL: "Shake out, breathe, reset rhythm", bL: "Reduce tries and increase rest plan" },
  { question: "When belaying a friend, your vibe is...", a: "Calm Connector", b: "Motivator", aL: "Steady, quiet reassurance", bL: "Loud support and hype" },
  { question: "On a volume-heavy route, you...", a: "Explorer", b: "Technician", aL: "Experiment with weird positions", bL: "Dial pressure and direction carefully" },
  { question: "Session notes usually include...", a: "Strategist", b: "Motivator", aL: "Goals hit, misses, next plan", bL: "Wins, stoke, and what felt great" },
  { question: "You arrive low energy. You...", a: "Calm Connector", b: "Risk-Taker", aL: "Take it easy and listen to body", bL: "Try one hard boulder to wake up" },
  { question: "Someone cuts in line unknowingly. You...", a: "Calm Connector", b: "Grinder", aL: "Politely clarify rotation", bL: "Wait and keep your focus" },
  { question: "Big coordination move coming. You...", a: "Risk-Taker", b: "Strategist", aL: "Launch and react mid-air", bL: "Practice timing and hand path first" },
  { question: "You flashed an unexpected hard climb. You think...", a: "Flow Climber", b: "Technician", aL: "Felt right, stayed present", bL: "Good execution of fundamentals" },
  { question: "You get one tip from a coach. You choose...", a: "Technician", b: "Explorer", aL: "Foot precision cue", bL: "Try more movement styles" },
  { question: "On rest between attempts, you...", a: "Strategist", b: "Motivator", aL: "Track timer and breathing", bL: "Chat and keep morale high" },
  { question: "A route has ugly beta. You...", a: "Explorer", b: "Grinder", aL: "Find your own creative sequence", bL: "Repeat the ugly beta until it works" },
  { question: "You prefer training blocks that are...", a: "Strategist", b: "Flow Climber", aL: "Structured with clear progression", bL: "Loose with room for feel" },
  { question: "When afraid of falling, you...", a: "Calm Connector", b: "Risk-Taker", aL: "Take controlled practice falls", bL: "Count down and commit" },
  { question: "Your climbing identity feels closest to...", a: "Technician", b: "Motivator", aL: "Craftsperson of movement", bL: "Energy source for the crew" },
  { question: "You keep missing a tiny crimp. You...", a: "Technician", b: "Grinder", aL: "Refine hand angle and thumb catch", bL: "Take more reps until it sticks" },
  { question: "Gym reset day arrives. You...", a: "Explorer", b: "Strategist", aL: "Try every new set possible", bL: "Pick targets by style and grade" },
  { question: "Friend is scared on top-out. You...", a: "Calm Connector", b: "Motivator", aL: "Give calm step-by-step cues", bL: "Cheer them through the final move" },
  { question: "If your skin is thin, you...", a: "Strategist", b: "Risk-Taker", aL: "Switch to technique mileage", bL: "Tape up and keep trying hard" },
  { question: "Your favorite progress metric is...", a: "Grinder", b: "Flow Climber", aL: "Attempts to send ratio improving", bL: "How effortless movement feels" },
  { question: "Someone asks for a spot. You...", a: "Calm Connector", b: "Technician", aL: "Stay attentive and communicate clearly", bL: "Position precisely for safe guidance" },
  { question: "You are strongest when conditions are...", a: "Risk-Taker", b: "Strategist", aL: "High pressure, little time", bL: "Predictable with clear prep" },
  { question: "On traverses, you focus on...", a: "Flow Climber", b: "Technician", aL: "Cadence and continuous motion", bL: "Quiet feet and exact placements" },
  { question: "Before touching a hard route, you...", a: "Strategist", b: "Explorer", aL: "Read and visualize all clips", bL: "Feel it out and adjust live" },
  { question: "Your post-fall self-talk sounds like...", a: "Motivator", b: "Grinder", aL: "You got this, next go!", bL: "Again. Cleaner this time." },
  { question: "A comp route has weird dual-tex holds. You...", a: "Explorer", b: "Technician", aL: "Test possibilities quickly", bL: "Find exact usable zones first" },
  { question: "At the end of session, you feel best if you...", a: "Flow Climber", b: "Strategist", aL: "Had good movement and fun", bL: "Checked off planned objectives" },
  { question: "You see a friend getting frustrated. You...", a: "Motivator", b: "Calm Connector", aL: "Boost their confidence loudly", bL: "Sit with them and lower pressure" },
  { question: "When trying hard, your breathing is...", a: "Calm Connector", b: "Risk-Taker", aL: "Controlled and steady", bL: "Fast, then all-in commit" },
  { question: "You choose drills that are mostly...", a: "Technician", b: "Grinder", aL: "Precision and efficiency focused", bL: "High repetition and endurance focused" },
  { question: "If a move is scary but possible, you...", a: "Risk-Taker", b: "Flow Climber", aL: "Send it with conviction", bL: "Wait for calm timing and then go" },
  { question: "You end up mentoring beginners by...", a: "Calm Connector", b: "Technician", aL: "Meeting them where they are", bL: "Teaching clear movement basics" },
  { question: "Hardest part of projects for you is...", a: "Explorer", b: "Grinder", aL: "Staying on one climb too long", bL: "Letting go when done for the day" },
  { question: "If you could instantly improve one thing...", a: "Strategist", b: "Motivator", aL: "Decision-making under fatigue", bL: "Confidence before every attempt" },
  { question: "Your ideal session end is...", a: "Flow Climber", b: "Risk-Taker", aL: "One smooth send to finish", bL: "One huge try, win or lose" },
  { question: "When a climb gets messy, you recover by...", a: "Technician", b: "Calm Connector", aL: "Re-centering on foot and hips", bL: "Slowing down and regulating breath" },
  { question: "If two climbs look equally good, you pick...", a: "Explorer", b: "Strategist", aL: "The weirder one", bL: "The one matching today's goal" },
  { question: "First time in a climbing gym, you are most likely to...", a: "Calm Connector", b: "Explorer", aL: "Watch others first and ease in slowly", bL: "Walk around and try whatever looks fun" },
  { question: "Before your first climb, you prefer...", a: "Strategist", b: "Risk-Taker", aL: "A quick demo of safety and basics", bL: "Learning by trying right away" },
  { question: "A route looks high and scary. You...", a: "Calm Connector", b: "Motivator", aL: "Start on an easier one to build confidence", bL: "Ask friends to hype you and go for it" },
  { question: "You miss a hold on your first attempt. You...", a: "Grinder", b: "Flow Climber", aL: "Try again with one tiny adjustment", bL: "Pause, reset, and move smoother next go" },
  { question: "A friend gives lots of tips. You prefer...", a: "Technician", b: "Explorer", aL: "One clear tip at a time", bL: "Trying different ideas until one clicks" },
  { question: "For your first session, success means...", a: "Flow Climber", b: "Strategist", aL: "Having fun and moving better", bL: "Completing the goals you set" },
  { question: "You are choosing your first climbs. You pick...", a: "Calm Connector", b: "Risk-Taker", aL: "The easiest color/grade to learn movement", bL: "A slightly harder one for the challenge" },
  { question: "When your hands get tired, you...", a: "Strategist", b: "Motivator", aL: "Rest properly before next attempt", bL: "Cheer yourself on and try again soon" },
  { question: "In a new social gym environment, you usually...", a: "Calm Connector", b: "Motivator", aL: "Keep it low-key and observe first", bL: "Talk to people and make it fun quickly" },
  { question: "If you do not know what to do on a climb, you...", a: "Technician", b: "Explorer", aL: "Look closely at hand/foot options", bL: "Test a few moves and learn by feel" },
  { question: "Your first climbing goal sounds like...", a: "Grinder", b: "Flow Climber", aL: "Finish one route cleanly, even if it takes tries", bL: "Move confidently without overthinking" },
  { question: "You are deciding between lesson or free climb. You choose...", a: "Strategist", b: "Risk-Taker", aL: "Lesson first so you start with good habits", bL: "Free climb first and figure things out" },
  { question: "After your first fall, your reaction is...", a: "Calm Connector", b: "Motivator", aL: "Take a breath and go again when ready", bL: "Laugh it off and jump back in" },
  { question: "A beginner friend asks you to join them. You...", a: "Calm Connector", b: "Motivator", aL: "Stay patient and support their pace", bL: "Keep energy high and celebrate every try" },
  { question: "At the end of your very first session, you are happiest if...", a: "Explorer", b: "Technician", aL: "You tried many different climbs", bL: "You learned a few solid fundamentals" },
];
